<?php

/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do NOT edit it manually. Run `php artisan openapi:generate-server`.
 */

use App\Http\ApiV1\Modules\Reservations\Controllers\ReservationsController;
use Illuminate\Support\Facades\Route;

Route::get('tables', [ReservationsController::class, 'getTablesList']);
Route::get('tables/status', [ReservationsController::class, 'getStatus']);
Route::post('reservations', [ReservationsController::class, 'createReservation']);
Route::delete('reservations/{id}', [ReservationsController::class, 'deleteReservation']);
