openapi: 3.0.3
info:
  title: Бронирование
  contact:
    name: API Support
    email: api-support@tables.ru
  version: 1.0.0
  description: Сервис для бронирования столиков
servers:
  - url: /api/v1
tags:
  - name: reservations
    description: Бронирование
paths:
  /tables/status:
    $ref: './reservations/paths.yaml#/Status'
  /reservations:
    $ref: './reservations/paths.yaml#/Reservation'
  /reservations/{id}:
    $ref: './reservations/paths.yaml#/DeleteReservation'
components:
  parameters:
    QueryInclude:
      $ref: './common_parameters.yaml#/QueryInclude'
    PathId:
      $ref: './common_parameters.yaml#/PathId'
  schemas:
    EmptyDataResponse:
      type: object
      properties:
        data:
          type: object
          nullable: true
        meta:
          type: object
      required:
          - data
    PaginationTypeEnum:
      $ref: './common_schemas.yaml#/PaginationTypeEnum'
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: './errors.yaml#/ErrorResponse'
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: './errors.yaml#/ErrorResponse'
    ServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: './errors.yaml#/ErrorResponse'
