openapi: 3.0.3
info:
  title: Бронирование
  contact:
    name: API Support
    email: api-support@tables.ru
  version: 1.0.0
  description: Сервис для бронирования столиков
servers:
  - url: /api/v1
tags:
  - name: reservations
    description: Бронирование
paths:
  /tables:
    $ref: './reservations/paths.yaml#/TablesList'
  /tables/status:
    $ref: './reservations/paths.yaml#/Status'
  /reservations:
    $ref: './reservations/paths.yaml#/Reservation'
  /reservations/{id}:
    $ref: './reservations/paths.yaml#/DeleteReservation'
components:
  securitySchemes:
    cookieAuth:
      description: Токен для проверки авторизации
      type: apiKey
      in: cookie
      name: token
      # example: ATAkNyqT7/uFFsw3GDRlRg==
  parameters:
    QueryInclude:
      $ref: './common_parameters.yaml#/QueryInclude'
    PathId:
      $ref: './common_parameters.yaml#/PathId'
  schemas:
    EmptyDataResponse:
      type: object
      properties:
        data:
          type: object
          nullable: true
        meta:
          type: object
      required:
        - data
    PaginationTypeEnum:
      $ref: './common_schemas.yaml#/PaginationTypeEnum'
  responses:
    BadRequest:
      description: Ошибка в запросе
      content:
        application/json:
          schema:
            $ref: './errors.yaml#/ErrorResponse'
    Unauthorized:
      description: Не авторизован
      content:
        application/json:
          schema:
            $ref: './errors.yaml#/ErrorResponse'
    NotFound:
      description: Не найдено
      content:
        application/json:
          schema:
            $ref: './errors.yaml#/ErrorResponse'
    ServerError:
      description: Ошибка на стороне сервера
      content:
        application/json:
          schema:
            $ref: './errors.yaml#/ErrorResponse'
